name: auto-update China Report Data

on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron: '0 6 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-22.04
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
      test_mail: ${{ vars.TEST_MAIL }}
      send_mail: ${{ vars.SEND_MAIL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12'

      - name: Install dependencies
        run: |
          pip install requests==2.31.0 xmltodict==0.13.0 beautifulsoup4==4.12.2 pandas==2.1.4 
          pip install reportlab==4.0.9 plotnine==0.12.4 onedrivedownloader==1.1.3 openpyxl==3.1.2 
          pip install tabulate==0.9.0 markdown==3.5.2 plotly==5.18.0 jinja2==3.1.3 openai==1.7.2 pyyaml==6.0.1 PyPDF2==3.0.1 Pillow==10.2.0

      - name: Run Python script
        run: |
          cd ./Script/CN
          python3 main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github action"
          git config --global user.email "lkg1116@users.noreply.github.com"
          git add .
          git commit -m "Auto update generated files"
          git push origin main
